"""Moss: Headless agent orchestration layer for AI engineering."""

from moss.anchors import (
    AmbiguousAnchorError,
    Anchor,
    AnchorMatch,
    AnchorNotFoundError,
    AnchorResolver,
    AnchorType,
    find_anchors,
    resolve_anchor,
)
from moss.context import CompiledContext, ContextHost, StaticContext
from moss.dependencies import (
    DependencyInfo,
    Export,
    Import,
    PythonDependencyProvider,
    extract_dependencies,
    format_dependencies,
)
from moss.events import Event, EventBus, EventType
from moss.handles import (
    BinaryFileHandle,
    DeferredHandle,
    FileHandle,
    Handle,
    HandleMetadata,
    HandleRef,
    HandleRegistry,
    MemoryHandle,
)
from moss.loop import (
    LoopConfig,
    LoopIteration,
    LoopResult,
    LoopStatus,
    SilentLoop,
    VelocityMetrics,
)
from moss.patches import (
    Patch,
    PatchResult,
    PatchType,
    apply_patch,
    apply_patch_with_fallback,
    apply_text_patch,
)
from moss.shadow_git import CommitHandle, GitError, ShadowBranch, ShadowGit
from moss.skeleton import (
    PythonSkeletonProvider,
    Symbol,
    extract_python_skeleton,
    format_skeleton,
)
from moss.validators import (
    CommandValidator,
    PytestValidator,
    RuffValidator,
    SyntaxValidator,
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
    Validator,
    ValidatorChain,
    create_python_validator_chain,
)
from moss.views import (
    Intent,
    RawViewProvider,
    View,
    ViewOptions,
    ViewProvider,
    ViewRegistry,
    ViewTarget,
    ViewType,
    create_default_registry,
)

__version__ = "0.1.0"

__all__ = [
    "AmbiguousAnchorError",
    "Anchor",
    "AnchorMatch",
    "AnchorNotFoundError",
    "AnchorResolver",
    "AnchorType",
    "BinaryFileHandle",
    "CommandValidator",
    "CommitHandle",
    "CompiledContext",
    "ContextHost",
    "DeferredHandle",
    "DependencyInfo",
    "Event",
    "EventBus",
    "EventType",
    "Export",
    "FileHandle",
    "GitError",
    "Handle",
    "HandleMetadata",
    "HandleRef",
    "HandleRegistry",
    "Import",
    "Intent",
    "LoopConfig",
    "LoopIteration",
    "LoopResult",
    "LoopStatus",
    "MemoryHandle",
    "Patch",
    "PatchResult",
    "PatchType",
    "PytestValidator",
    "PythonDependencyProvider",
    "PythonSkeletonProvider",
    "RawViewProvider",
    "RuffValidator",
    "ShadowBranch",
    "ShadowGit",
    "SilentLoop",
    "StaticContext",
    "Symbol",
    "SyntaxValidator",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
    "Validator",
    "ValidatorChain",
    "VelocityMetrics",
    "View",
    "ViewOptions",
    "ViewProvider",
    "ViewRegistry",
    "ViewTarget",
    "ViewType",
    "apply_patch",
    "apply_patch_with_fallback",
    "apply_text_patch",
    "create_default_registry",
    "create_python_validator_chain",
    "extract_dependencies",
    "extract_python_skeleton",
    "find_anchors",
    "format_dependencies",
    "format_skeleton",
    "resolve_anchor",
]
