"""Command-line interface for Moss.

This package provides the CLI entry point.

Structure:
- _main.py: All commands (5687 lines, to be split incrementally)
- _common.py: Shared utilities (setup_output, wants_json, etc.)

Planned splits (not yet done):
- analysis.py: complexity, clones, security, patterns, weaknesses, coverage, lint, etc.
- editing.py: edit, mutate, synthesize, check_refs
- navigation.py: search, context, cfg, deps
- servers.py: mcp_server, acp_server, lsp
- workflow.py: run, workflow, agent, eval

# See: docs/cli/commands.md
"""

# Re-export everything from _main for backwards compatibility
from moss.cli._main import (
    cmd_acp_server,
    cmd_agent,
    cmd_analyze_session,
    cmd_cfg,
    cmd_check_refs,
    cmd_checkpoint,
    cmd_clones,
    cmd_complexity,
    cmd_config,
    cmd_context,
    cmd_coverage,
    cmd_deps,
    cmd_diff,
    cmd_diff_preferences,
    cmd_distros,
    cmd_edit,
    cmd_eval,
    cmd_explore,
    cmd_external_deps,
    cmd_extract_preferences,
    cmd_gen,
    cmd_git_hotspots,
    cmd_help,
    cmd_hooks,
    cmd_init,
    cmd_lint,
    cmd_lsp,
    cmd_mcp_server,
    cmd_metrics,
    cmd_mutate,
    cmd_overview,
    cmd_patterns,
    cmd_pr,
    cmd_query,
    cmd_rag,
    cmd_report,
    cmd_roadmap,
    cmd_rules,
    cmd_run,
    cmd_search,
    cmd_security,
    cmd_shell,
    cmd_status,
    cmd_synthesize,
    cmd_telemetry,
    cmd_toml,
    cmd_tui,
    cmd_watch,
    cmd_weaknesses,
    cmd_workflow,
    create_parser,
    get_version,
    main,
    output_result,
    setup_output,
    wants_json,
)

__all__ = [
    "cmd_acp_server",
    "cmd_agent",
    "cmd_analyze_session",
    "cmd_cfg",
    "cmd_check_refs",
    "cmd_checkpoint",
    "cmd_clones",
    "cmd_complexity",
    "cmd_config",
    "cmd_context",
    "cmd_coverage",
    "cmd_deps",
    "cmd_diff",
    "cmd_diff_preferences",
    "cmd_distros",
    "cmd_edit",
    "cmd_eval",
    "cmd_explore",
    "cmd_external_deps",
    "cmd_extract_preferences",
    "cmd_gen",
    "cmd_git_hotspots",
    "cmd_help",
    "cmd_hooks",
    "cmd_init",
    "cmd_lint",
    "cmd_lsp",
    "cmd_mcp_server",
    "cmd_metrics",
    "cmd_mutate",
    "cmd_overview",
    "cmd_patterns",
    "cmd_pr",
    "cmd_query",
    "cmd_rag",
    "cmd_report",
    "cmd_roadmap",
    "cmd_rules",
    "cmd_run",
    "cmd_search",
    "cmd_security",
    "cmd_shell",
    "cmd_status",
    "cmd_synthesize",
    "cmd_telemetry",
    "cmd_toml",
    "cmd_tui",
    "cmd_watch",
    "cmd_weaknesses",
    "cmd_workflow",
    "create_parser",
    "get_version",
    "main",
    "output_result",
    "setup_output",
    "wants_json",
]
